# Generated by Django 4.2.1 on 2023-12-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_talk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("phone", models.CharField(max_length=15, verbose_name="telefone")),
                ("message", models.CharField(max_length=1023, verbose_name="mensagem")),
            ],
            options={
                "verbose_name": "contato",
                "verbose_name_plural": "contatos",
            },
        ),
    ]
