# Generated by Django 4.2.1 on 2023-12-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.CharField(
                blank=True, max_length=1023, verbose_name="mensagem"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=15, verbose_name="telefone"),
        ),
    ]
