# Generated by Django 4.2.1 on 2023-12-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='telefone')),
                ('message', models.TextField(max_length=1023, verbose_name='mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='realizado em')),
                ('response', models.TextField(blank=True, verbose_name='resposta')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='atualizado em')),
                ('replied', models.BooleanField(default=False, verbose_name='respondido')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
                'ordering': ['-created_at', 'replied'],
            },
        ),
    ]
