# Generated by Django 4.2.1 on 2023-12-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at', 'replied'], 'verbose_name': 'contato', 'verbose_name_plural': 'contatos'},
        ),
        migrations.AddField(
            model_name='contact',
            name='replied',
            field=models.BooleanField(default=False, verbose_name='respondido'),
        ),
        migrations.AddField(
            model_name='contact',
            name='reply',
            field=models.TextField(blank=True, verbose_name='resposta'),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
    ]
