# Generated by Django 4.2.1 on 2023-12-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_options_contact_replied_contact_reply_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='reply',
            new_name='response',
        ),
    ]
