# Generated by Django 4.2.1 on 2023-12-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_reply_contact_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(verbose_name='atualizado em'),
        ),
    ]
